### ISSUE TITLE
Add "105 Fonds travaux" on the 'plan comptable' for France

### ISSUE THREAD

**Issue by romjerome** [Diacamma2/syndic#3]
According to [last definitions and hierarchies](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000033724160) I suppose that the 'plan comptable' for France should add a "105 Fonds travaux" line.

```diff
code;name
102;Provisions pour travaux décidés
103;Avances	
1031;Avances de trésorerie	
1032;Avances travaux au titre de l'article 18.6e alinéa de la loi susvisée
1033;Autres avances
+105;Fonds travaux	
120;Solde en attente sur travaux et opérations exceptionnelles
131;Subventions accordées en instance de versement 
```
../diacamma/syndic/init_french.csv

Note: Github is pointing out a possible typo on this file:

> "We can make this file beautiful and searchable if this error is corrected: It looks like row 22 should actually have 1 column, instead of 2."

Anyway, it looks like a 'false positive' as the current separator is not a comma.

**Comment by romjerome** [comment]
mmmh, it looks like not really (always?) right ...

> "Les règles comptables spécifiques prévues par le présent décret s'appliquent uniquement aux syndicats de copropriétaires. Elles ne s'appliquent pas à la comptabilité du syndic, qui obéit à ses règles propres, ni à la comptabilité d'autres entités telles que les unions de syndicats ou les associations syndicales régies par l'ordonnance du 1er juillet 2004 susvisée. Les statuts de ces dernières peuvent, toutefois, prévoir que leurs comptes sont tenus conformément aux règles comptables propres aux syndicats de copropriétaires, à l'exception des associations assujetties de plein droit au règlement n° 99-01 de l'Autorité des normes comptables."

**Comment by romjerome** [comment]
There is also an other addition:


```diff
450;Copropriétaire individualisé
4501;Copropriétaire - budget prévisionnel
4502;Copropriétaire - travaux et opération exceptionnelles
4503;Copropriétaire - avances
4504;Copropriétaire - emprunts
+4505 Copropriétaire - fonds de travaux 
459;Copropriétaire - créances douteuses
```
../diacamma/syndic/init_french.csv

**Comment by romjerome** [comment]
And a last one:

```diff
701;Appels de fonds - Provisions sur opérations courantes
702;Appels de fonds - Provisions sur travaux de l'article 14-2 et opérations exceptionnelles
703;Appels de fonds - Avances
704;Appels de fonds - Remboursements d'annuités d'emprunts
+705;Affectation fonds de travaux
711;Subventions
712;Emprunts
```

**Comment by GayLaurent** [comment]
thanks,

Yes, it is relative of the new french law of december 2016.
Before add those 3 accounts, it's important to understand how use them.

To study, so ;)

**Comment by romjerome** [comment]
Je n'ai que de vagues notions de comptabilité...

Pour ma part, j'assigne la quote-part d'un copropriétaire au fonds pour travaux dans son compte dédié (45x5) et le total apparaît dans le compte global (105).

Le compte 705 sera utilisé si des travaux utilisant ce fonds sont réalisés.

Comme mentionné dans #1 j'utilise actuellement un plan comptable personnalisé dans GnuCash (ajout de comptes "dettes" aux copropiétaires, ainsi qu'un compte après l'AG dans lequel apparaît le montant voté dans le budget prévisionnel).

Au final, cela se rapproche, d'après moi, de la saisie "**travaux votés à l'AG**" et les quotes-parts des copropiétaires, sauf que certains comptes ne seront pas "_remis à zéro_" après la fin de l'exercice... Par ailleurs est-ce que l'**affectation du fonds pour travaux** n'est elle pas également **votée en AG** ???

La relation "**compte rémunéré**" et "**fonds pour travaux**" apparaît également dans mon bilan même si l'affectation des intérêts n'est malheureusement pas claire: quote-part sur des intérêts ? basée sur quelle grille de répartition ??? quid des frais de banque ?

**Comment by GayLaurent** [comment]
Je vous invite à consulter le forum dédié à _Diacamma_: [http://www.diacamma.org/forum/](http://www.diacamma.org/forum/)
Vous pourrez y trouver des conseils et poser vos questions.
Ce sera plus simple que via le gestionnaire de défaut de github

**Comment by romjerome** [comment]
> Diacamma Syndic
> 
>     Gestion du 'fond travaux'.
>     De nouveaux codes comptables "fond de travaux" sont maintenant accessibles.
>     Un nouvelle type appel de fonds est également ajouté pour le prendre en compte.
> 

Merci ! :1st_place_medal: 

```
Name: diacamma-syndic
Version: 2.1.15.17092813
```

Je ne vois pas de support pour le "fonds de travaux" dans le fichier 'init_french.csv' (dernière révision). Comment peut-on accéder à ces nouveaux codes ?

ps : il me semble que dans ce contexte, "fonds" a toujours un "s" à la fin.

**Comment by GayLaurent** [comment]
Oups, en effet, le fichier "init_french.csv" n'a pas été complété.

En faite, dans la correction, ce n'était pas là la complexité, c'était plutôt d'ajouter les différents paramètres de gestion (menu "Administration > Configuration de la coproriété"), de les gérer correctement via l'appel de fonds correspondant.

Il est de tout façon toujours possible d'ajouter les 3 codes comptes manquants directement à la mains (menu "Financier > plan comptable", bouton "Ajouter")
Le fichier "init_french.csv" sera corrigé pour la prochaine mise à jour.

Merci de votre retour.

**Comment by romjerome** [comment]
> ajouter les différents paramètres de gestion (menu "Administration > Configuration de la coproriété"), de les gérer correctement via l'appel de fonds correspondant.

À la lecture des derniers commits, j'ai bien [vu ces codes dans le code](https://github.com/Diacamma2/syndic/commit/b22454ad7b7269dc1decd531979768e4e06fe1df).

> Il est de tout façon toujours possible d'ajouter les 3 codes comptes manquants directement à la mains (menu "Financier > plan comptable", bouton "Ajouter")

Effectivement, c'était juste un peu étrange de ne pas les trouver dans le fichier.

Merci.
