### ISSUE TITLE
Envoi des appels de fonds (mail), mauvaise extension de fichier

### ISSUE THREAD

**Issue by Nonobis** [Diacamma2/syndic#41]
Lors d'un envoi d'un appel de fond, l'extension de la pj n'est pas .pdf mais .dat.
Y'a t'il moyen de modifer ? Cela perturbe certain co-propriétaire.

Merci

**Comment by GayLaurent** [comment]
Bonjour,

Ce comportement est réalisé par le fournisseur de courrier électronique.
Dans le cas où il considère l'envoie du message "non totalement sécurisé", les pièces jointes sont remplacés par une autre indiquant.
Pour résoudre il faut avoir un envoie de courriel irréprochable (message signé et adresse confirmée).

**Comment by Nonobis** [comment]
Bonjour,

Merci pour votre réponse, j'utilise le compte Gmail crée pour la copropriété. Je vais voir s'il y'a moyen d'avoir au moins l'adresse confirmé.
